### PR TITLE
Fix firefox bugs

### LINKED ISSUE #562: Duplicated commit strings in some firefox sites
# Example

https://discord.com/app

# Summary

`오[랜]` + `ㅁ` = `오랜ㅁ랜ㅁ|` not `오랜[ㅁ]`

# Detail

Due to #535, gtk frontend call `update_preedit(FALSE)` to end preedit state before commit

It's because chromium doesn't update preedit string when preedit string is same as before, but this can't handle `[ㅋ]` + `ㅋ` = `ㅋ[ㅋ]` case

So kime now always end preedit state before commit but this produced another bug.

In above site, it commits `reset` when preedit was ended (it's not always occurred but I'm not sure exact condition).
When this occurred in middle of commit process, it'll double commit string. Furthermore, preedit state also be terminated.

Note that this only affects develop branch, since #536 has not been released.

### PR DESCRIPTION
**Pull request by Riey**
Fix #562
Fix #563

## Summary

Create new flag `is_committing` it checks whether reset event is real or dummy.

## Checklist

- [x] I have documented my changes properly to adequate places
- [x] I have updated the docs/CHANGELOG.md

### CODE REVIEW

File: src/frontends/gtk2/src/immodule.c [hunk 1]
```diff
@@ -69,6 +75,7 @@ void update_preedit(KimeImContext *ctx, gboolean visible) {
 
 void commit(KimeImContext *ctx) {
   // https://github.com/Riey/kime/issues/535
+  ctx->is_committing = TRUE;
```
Comment (Riey) [inline src/frontends/gtk2/src/immodule.c:78]: I forgot to set flag FALSE after call update_preedit :(

Comment (Riey) [reply src/frontends/gtk2/src/immodule.c:78]: Should be fixed in #565
